import createActions from 'utils/createActions';

export const actionLabels = {
  FETCH_ALL_CAMPAIGNS: 'FETCH_ALL_CAMPAIGNS',
  FETCH_ALL_CAMPAIGNS_SUCCESS: 'FETCH_ALL_CAMPAIGNS_SUCCESS',
  FETCH_ALL_CAMPAIGNS_ERROR: 'FETCH_ALL_CAMPAIGNS_ERROR',
  SELECT_CAMPAIGN: 'SELECT_CAMPAIGN',
  FETCH_CAMPAIGN_DETAILS: 'FETCH_CAMPAIGN_DETAILS',
  FETCH_CAMPAIGN_DETAILS_SUCCESS: 'FETCH_CAMPAIGN_DETAILS_SUCCESS',
  FETCH_CAMPAIGN_DETAILS_ERROR: 'FETCH_CAMPAIGN_DETAILS_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',
};

export default { ...actionLabels, ...createActions(actionLabels), };
